/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "on-background": "#2d2f2f",
        "surface-dim": "#d3d5d5",
        "surface-bright": "#f6f6f6",
        "secondary": "#155e9a",
        "surface": "#f6f6f6",
        "on-secondary-container": "#004a7d",
        "on-primary-container": "#005c15",
        "tertiary-fixed": "#ff9655",
        "inverse-primary": "#9df197",
        "secondary-dim": "#00528b",
        "tertiary-container": "#ff9655",
        "on-primary-fixed-variant": "#12661e",
        "on-error": "#ffefee",
        "inverse-surface": "#0c0f0f",
        "primary-fixed": "#9df197",
        "surface-container-high": "#e1e3e3",
        "on-secondary-fixed": "#00365e",
        "inverse-on-surface": "#9c9d9d",
        "surface-container-low": "#f0f1f1",
        "primary-container": "#9df197",
        "error-container": "#fb5151",
        "on-tertiary-fixed": "#2d0f00",
        "outline-variant": "#acadad",
        "on-tertiary-fixed-variant": "#612900",
        "outline": "#767777",
        "surface-container": "#e7e8e8",
        "background": "#f6f6f6",
        "surface-container-highest": "#dbdddd",
        "tertiary-dim": "#843a00",
        "on-secondary-fixed-variant": "#00538d",
        "on-surface": "#2d2f2f",
        "surface-tint": "#176a21",
        "secondary-fixed": "#b3d4ff",
        "on-primary-fixed": "#00460e",
        "primary-dim": "#025d16",
        "primary-fixed-dim": "#90e28a",
        "primary": "#176a21",
        "on-secondary": "#edf3ff",
        "on-tertiary-container": "#532200",
        "on-tertiary": "#fff0e9",
        "surface-variant": "#dbdddd",
        "on-surface-variant": "#5a5c5c",
        "tertiary-fixed-dim": "#f6853b",
        "tertiary": "#964300",
        "secondary-fixed-dim": "#98c7ff",
        "error-dim": "#9f0519",
        "on-primary": "#d1ffc8",
        "on-error-container": "#570008",
        "error": "#b31b25",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#b3d4ff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Be Vietnam Pro"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
}
